dbpunk-labs/db3

.github/workflows/ci.yml
proto/rtstore_compute_node.proto
src/compute_node/compute_node_impl.rs
src/compute_node/sql_engine.rs
src/frontend_node/mysql/mysql_handler.rs
src/frontend_node/mysql/sql_handler.rs
src/sdk/compute_node_sdk.rs

feat: support connection_id and current user

---

.github/workflows/ci.yml
.gitmodules
Cargo.toml
README.md
src/base/arrow_parquet_utils.rs
src/catalog/catalog.rs
src/catalog/table.rs
src/catalog/table_scanner.rs
src/codec/flight_codec.rs
src/compute_node/compute_node_impl.rs
src/compute_node/sql_engine.rs
src/frontend_node/mysql/mysql_vars.rs
src/frontend_node/mysql/sql_handler.rs
src/memory_node/memory_node_impl.rs
src/meta_node/meta_server.rs
src/sdk/compute_node_sdk.rs
src/sdk/memory_node_sdk.rs
src/sdk/meta_node_sdk.rs
src/store/object_store.rs

fix: use thirdparty path as dependency

---

.github/labeler.yml
.github/workflows/ci.yml
.github/workflows/labeler.yaml
.gitmodules
Cargo.toml
README.md
src/base/arrow_parquet_utils.rs
src/catalog/catalog.rs
src/catalog/table.rs
src/catalog/table_scanner.rs
src/codec/flight_codec.rs
src/compute_node/compute_node_impl.rs
src/compute_node/sql_engine.rs
src/frontend_node/mysql/mysql_vars.rs
src/frontend_node/mysql/sql_handler.rs
src/memory_node/memory_node_impl.rs
src/meta_node/meta_server.rs
src/sdk/compute_node_sdk.rs
src/sdk/memory_node_sdk.rs
src/sdk/meta_node_sdk.rs
src/store/object_store.rs

change titile4

---

frame/db/src/lib.rs

feat: unifiy the return data format

---

Cargo.toml
kvstore/Cargo.toml
kvstore/Readme.md
kvstore/src/lib.rs
kvstore/src/main.rs
kvstore/tests/kvstore_app.rs

Initialize a development environment based on [tendermint-rs](https://github.com/informalsystems/tendermint-rs)

Add kvstore app implemented with tindermint abci

---

README.md
tools/start_localnet.sh

121 support restarting abci and recover root hash and height

---

.github/workflows/cd.yml

feat: add ubuntu and mac cd

---

src/node/Cargo.toml
src/node/src/abci_impl.rs
src/node/src/main.rs
src/node/src/node_config.rs
src/node/src/storage_node_impl.rs
src/node/tests/node_test.rs
src/sdk/src/mutation_sdk.rs
src/sdk/src/store_sdk.rs
src/session/src/session_manager.rs
src/types/src/account_key.rs
src/types/src/bill_key.rs
tools/start_localnet.sh

feat: stop the progress of db3 gracefully

---

src/node/src/abci_impl.rs
src/sdk/Cargo.toml
src/sdk/src/mutation_sdk.rs
src/sdk/src/store_sdk.rs
src/storage/src/kv_store.rs

feat: check the valid of mutation

---

src/base/src/strings.rs
src/cmd/src/lib.rs
src/types/src/cost.rs
src/types/src/gas.rs

fix: fix the key path bug

---

.github/workflows/ci.yml
README.md
src/cmd/src/lib.rs

fix: update readme and recover the coverage

---

src/cmd/src/lib.rs

fix: fix  compile error

---

.github/workflows/cd.yml
src/db3js/package.json

fix: auto release db3js

---

src/node/Cargo.toml
src/node/src/hash_util.rs
src/node/src/json_rpc_impl.rs
src/node/src/storage_node_impl.rs
src/sdk/Cargo.toml

fix: upgrade tendermint-rs to 0.27.0

---

src/db3js/src/lib/db3.test.ts
src/db3js/src/lib/db3.ts
src/db3js/src/lib/doc_store.ts

delete data by key

---

tools/start_localnet.sh

revert start tm and start node

---

src/db3js/package.json
src/db3js/src/lib/db3.ts
src/db3js/src/lib/doc_store.ts
src/db3js/src/lib/keys.ts

fix: add no ts check

---

src/node/Cargo.toml
src/sdk/src/store_sdk.rs
src/session/src/query_session_verifier.rs

fix: upgrade tendermint to 0.28.0

---

src/db3js/package.json
src/db3js/src/benches/async_exp.ts
src/db3js/src/benches/reduce.ts
src/db3js/src/benches/sdk_query.ts
src/db3js/src/lib/db3.ts
src/db3js/yarn.lock

```
yarn install
yarn benny-demo
```
Result
```
yarn benny-sdk
```
compile failure
```
❯ yarn benny-sdk                                                                                                                                                               ─╯
yarn run v1.22.19
warning package.json: No license field
warning ../../../../../package.json: No license field
$ ts-node-esm ./src/benches/sdk_query.ts
/Users/chenjing/work/dbpunk/db3/src/db3js/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
throw new ERR_MODULE_NOT_FOUND(
^
CustomError: Cannot find module '/Users/chenjing/work/dbpunk/db3/src/db3js/src/lib/db3' imported from /Users/chenjing/work/dbpunk/db3/src/db3js/src/benches/sdk_query.ts
at finalizeResolution …
```

add benny benchmark framework into db3 and add demo test

---

README.md

update readme add gitpoap badge

---

README.md

update readme grammar

---

README.md
README_zh_cn.md

fix: add zh_cn

---

README.md

update readme: add filecoin logo

---

README.md

update readme: add discord badge and link

---

src/node/src/storage_node_impl.rs
src/sdk/benches/submit_mutation_benchmark.rs

fix: update merkdb

---

src/proto/proto/README.md
src/proto/proto/compile.sh
src/proto/proto/firestore/bundle.proto
src/proto/proto/firestore_bundle_proto.ts
src/proto/proto/firestore_proto_api.ts
src/proto/proto/google/api/annotations.proto
src/proto/proto/google/api/client.proto
src/proto/proto/google/api/field_behavior.proto
src/proto/proto/google/api/http.proto
src/proto/proto/google/firestore/v1/aggregation_result.proto
src/proto/proto/google/firestore/v1/common.proto
src/proto/proto/google/firestore/v1/document.proto
src/proto/proto/google/firestore/v1/firestore.proto
src/proto/proto/google/firestore/v1/query.proto
src/proto/proto/google/firestore/v1/write.proto
src/proto/proto/google/protobuf/any.proto
src/proto/proto/google/protobuf/descriptor.proto
src/proto/proto/google/protobuf/empty.proto
src/proto/proto/google/protobuf/struct.proto
src/proto/proto/google/protobuf/timestamp.proto
src/proto/proto/google/protobuf/wrappers.proto
src/proto/proto/google/rpc/status.proto
src/proto/proto/google/type/latlng.proto
src/proto/proto/protos.json
src/proto/proto/update.sh

feat: add firestore protobuf

---

README.md
README_zh_cn.md

feat: update zh cn readme

---

README.md

readme: grammer and new line

---

README.md

update readme doc link path

---

src/cmd/src/command.rs
src/node/src/auth_storage.rs
src/node/src/storage_node_impl.rs
src/proto/proto/db3_database.proto
src/proto/proto/db3_node.proto
src/sdk/src/store_sdk.rs
src/storage/src/db_store.rs

Resolve part of work from #271 
```
██████╗ ██████╗ ██████╗
██╔══██╗██╔══██╗╚════██╗
██║  ██║██████╔╝ █████╔╝
██║  ██║██╔══██╗ ╚═══██╗
██████╔╝██████╔╝██████╔╝
╚═════╝ ╚═════╝ ╚═════╝
@db3.network🚀🚀🚀
db3>-$ init
Init key successfully!
db3>-$ new-db
database address                           | transaction id
--------------------------------------------+----------------------------------------------
0xbdc757f3fab64128240f84014cf27c9f65573260 | nTf7vLK1mrwrfcvkNYd4n+S6TMH1XoTSCZBn/0Dn3Wk=
db3>-$ new-collection --addr 0xbdc757f3fab64128240f84014cf27c9f65573260 --name books --index '{"id":1,"name":"idx1","fields":[{"field_path":"name","value_mode":{"Order":1}}]}'
send add collection done with tx
7Pwjw8WUB5w+kWY58E0gWBM4FvH3gFjgp7BVDEKceqE=
db3>-$ new-collection --addr …
```

support get-doc command cli and GetDocument API

---

src/cmd/src/command.rs
src/cmd/src/console.rs
src/cmd/src/keystore.rs
src/node/src/command.rs

add command test to increase the coverage

---

CONTRIBUTING.md

feat: add steps for updating document

---

README.md

fix readme grammar ”a -> an“

---

src/base/src/bson_util.rs
src/cmd/src/command.rs
src/error/src/lib.rs
src/node/src/command.rs
src/proto/proto/db3_mutation.proto
src/sdk/src/sdk_test.rs
src/storage/src/db_store.rs

- `update-doc --addr db_addr --collection-name collectionxxxxxx --ids=doc_id_xxxxx --documents '{"field1": value2, "field2": value2}' --masks 'filed1, field2, filed3delted'`
```
██████╗ ██████╗ ██████╗
██╔══██╗██╔══██╗╚════██╗
██║  ██║██████╔╝ █████╔╝
██║  ██║██╔══██╗ ╚═══██╗
██████╔╝██████╔╝██████╔╝
╚═════╝ ╚═════╝ ╚═════╝
@db3.network🚀🚀🚀
db3>-$ init
address                                    | scheme
--------------------------------------------+-----------
0x84b0bd55e7ad979b7cb92a56f561190de8f68403 | secp256k1
db3>-$ new-db
database address                           | transaction id
--------------------------------------------+----------------------------------------------
0xf7445b5438d6177b556a5d0d09b75af4ae2a2277 | SLMByMr1p47/YMpy1uHksP+hkmxBGhX7RW2Yx+3jvvo=
db3>-$ new-collection …
```

add update mask and cmd update-doc with mask

---

.github/workflows/cd.yml
src/storage/src/db_store.rs

fix: fix cicd

---

README.md

add todomvc DEMO

---

README.md
src/bridge/Cargo.toml
src/storage/Cargo.toml
src/storage/src/db3_document.rs
src/storage/src/db_store.rs

Optimize the  limited query

---

src/cmd/src/command.rs
src/crypto/src/db3_address.rs
src/node/Cargo.toml
src/node/src/abci_impl.rs
src/node/src/command.rs
src/node/src/context.rs
src/node/src/lib.rs
src/node/src/storage_node_impl.rs
src/proto/proto/db3_event.proto
src/proto/proto/db3_node.proto
src/sdk/Cargo.toml
src/sdk/src/store_sdk.rs

1. confirm the mutation has been applied successfully 
2. get the real-time  notification about the data updates

feat: event push support

---

README.md
install_env.sh
tools/db3up
tools/start_localnet.sh

fix: add db3up

---

src/base/src/bson_util.rs
src/cmd/src/command.rs
src/crypto/src/db3_keypair.rs
src/node/src/command.rs

- cmd create collection with json index string: `--index '{"name":"idx1","fields":[{"field_path":"test1","value_mode":{"Order":1}}]}'
send add collection done!`
Resolve #340 
```
❯ ./target/debug/db3 console                                                                                                                                                   ─╯
██████╗ ██████╗ ██████╗
██╔══██╗██╔══██╗╚════██╗
██║  ██║██████╔╝ █████╔╝
██║  ██║██╔══██╗ ╚═══██╗
██████╔╝██████╔╝██████╔╝
╚═════╝ ╚═════╝ ╚═════╝
@db3.network🚀🚀🚀
db3>-$ init
address                                    | scheme
--------------------------------------------+-----------
0x84b0bd55e7ad979b7cb92a56f561190de8f68403 | secp256k1
db3>-$ new-db
database address                           | mutation id …
```

remove id from cmd index

---

README.md

fix: fix db3.js example

---

.github/workflows/cd.yml
config/devnet/genesis.json
src/node/src/command.rs
src/node/src/context.rs
src/node/src/storage_node_impl.rs
src/proto/proto/db3_node.proto
src/sdk/src/store_sdk.rs
tools/db3up

feat: add disable query session flag

---

docs/index.md
mkdocs.yml

feat: improve the document

---

CONTRIBUTING.md

feat: update the steps about how to run test cases

---

.github/workflows/cd.yml
.github/workflows/ci.yml
src/node/Cargo.toml
src/node/src/abci_impl.rs
src/node/src/node_key.rs
tools/start_localnet.sh

fix: upgrade tendermint  to v0.30.0

---

CONTRIBUTING.md
docs/index.md

fix: update the contract building steps

---

src/storage/src/db_store.rs

Resolve  #402 
refactor run query to query with given Index range and limit

add execute query with indexId range and limit

---

docs/build/quick_start.md

fix  markdown error on quick_start.md
